name: Create Docker Container

on:
  push:
  Workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chceckout Preps
        uses: actions/checkout@v4
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Setup Docker Compose
      #   env:
      #     BRANCH_NAME: ${GITHUB_REF##*/}
        # run: docker-compose -f ../../init/docker/docker-compose.yaml up --build
      # - uses: isbang/compose-action@v1.5.1
      #   name: Setup docker compose up
      #   with:
      #     compose-file: "./../../init/docker/docker-compose.yaml"
      #     up-flags: "--build"
      #   env:
      #     BRANCH_NAME: ${GITHUB_REF##*/}
      - name: Setup docker compose up
        run: |
          cd docker
          ls
